### PR TITLE
update chacha20 lib to github.com/aead/chacha20

### PR DESCRIPTION
**Pull request by cn4**
to reduce dependencies.

-- github.com/mzz2017/shadowsocksR/streamCipher
--- gitlab.com/yawning/chacha20.git
---- gitlab.com/yawning/chacha20.git.test
----- github.com/stretchr/testify/require
------ github.com/stretchr/testify/assert
------- gopkg.in/yaml.v2
-------- gopkg.in/yaml.v2.test

### CODE REVIEW

**Comment by mzz2017** [comment]
Thanks but this looks like not necessary. :)

**Comment by mzz2017** [comment]
Is it works fine?
And it remains considerable if it optimizes performance.

**Comment by westhiker** [comment]
```
package main

import (
	"testing"

	"github.com/aead/chacha20"
	ychacha20 "gitlab.com/yawning/chacha20.git"
)

func benchmarkCipher(b *testing.B, size int, nonceSize int) {
	var key [32]byte
	nonce := make([]byte, nonceSize)
	c, _ := chacha20.NewCipher(nonce, key[:])
	buf := make([]byte, size)

	b.SetBytes(int64(len(buf)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		c.XORKeyStream(buf, buf)
	}
}

func benchmarkYCipher(b *testing.B, size int, nonceSize int) {
	var key [32]byte
	nonce := make([]byte, nonceSize)
	c, _ := ychacha20.New(key[:], nonce)
	buf := make([]byte, size)

	b.SetBytes(int64(len(buf)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		c.XORKeyStream(buf, buf)
	}
}

func BenchmarkChaCha20_Nonce8(b *testing.B)   { benchmarkCipher(b, 64, 8) }
func BenchmarkChaCha20_Nonce12(b *testing.B)  { benchmarkCipher(b, 64, 12) }
func BenchmarkChaCha20_Nonce24(b *testing.B)  { benchmarkCipher(b, 64, 24) }
func BenchmarkYChaCha20_Nonce8(b *testing.B)  { benchmarkYCipher(b, 64, 8) }
func BenchmarkYChaCha20_Nonce12(b *testing.B) { benchmarkYCipher(b, 64, 12) }
func BenchmarkYChaCha20_Nonce24(b *testing.B) { benchmarkYCipher(b, 64, 24) }

```

```
goos: darwin
goarch: amd64
pkg: chacha20test
BenchmarkChaCha20_Nonce8-16      	14320611	        78.2 ns/op	 818.48 MB/s	       0 B/op	       0 allocs/op
BenchmarkChaCha20_Nonce12-16     	14883685	        78.3 ns/op	 817.06 MB/s	       0 B/op	       0 allocs/op
BenchmarkChaCha20_Nonce24-16     	14923488	        78.7 ns/op	 812.74 MB/s	       0 B/op	       0 allocs/op
BenchmarkYChaCha20_Nonce8-16     	13522338	        80.4 ns/op	 796.16 MB/s	       0 B/op	       0 allocs/op
BenchmarkYChaCha20_Nonce12-16    	14684907	        79.3 ns/op	 806.62 MB/s	       0 B/op	       0 allocs/op
BenchmarkYChaCha20_Nonce24-16    	14885949	        79.4 ns/op	 805.69 MB/s	       0 B/op	       0 allocs/op
PASS
ok  	chacha20test	8.033s
```

**Comment by westhiker** [comment]
I tried to use official chacha20 package in PR #9, but then I found it doesn't support nonce size 8. 

In the official issue https://github.com/golang/go/issues/24485, I found this new package and it's a bit quicker than the old one.

**Comment by mzz2017** [comment]
They look the same performance. And thanks for your tests.

Keep in touch if there is new progress.

**Pull request closed without merging**
