### PR TITLE
validate the checksum

### PR DESCRIPTION
**Pull request by goomadao**
https://github.com/shadowsocksr-backup/shadowsocksr/blob/manyuser/shadowsocks/obfsplugin/auth.py#L611,L614

### CODE REVIEW

**Comment by nadoo** [comment]
@mzz2017 @goomadao is there any issue with this PR?

**Comment by goomadao** [comment]
yes, I used the wrong variable. It should be `length` instead of `plainLength`. Sorry for that.

**Comment by mzz2017** [comment]
I will add version information to the lib later.

**Comment by nadoo** [comment]
Thanks bro!

**Pull request merged**
